### ISSUE TITLE
o/ performance improvement suggestion

### ISSUE THREAD

**Issue by Speiger** [Estrogenized/needle#1]
o/ This library looks kinda cool!
While looking through it i found something that can give a massive performance boost in your collections.
https://github.com/Estrogenized/needle/blob/mistress/src/main/java/moe/queery/needle/collection/evicting/EvictingCollection.java#L23
Instead of using toArray() and effectively arraycopying a LinkedList you can use collection.iterator().next();
Which just provides exactly what you want but with way less overhead.
Also with the list implementation remove(0) is faster with LinkedLists,

**Comment by lumii500pg** [comment]
Now fixed it in b4185888dbbcae23dfb530ca62bfcfb0cd96c49d ✨
Thank you so much for the suggestion. :3
